# _quarto.yml

project:
  type: website
  render:
    - index.qmd
    - pages/**/*.qmd
    - slides/**/*.qmd
  resources:
    - classlib/classlib/quarto/slides/hickernell-latex-macros.js
    - classlib/classlib/quarto/assets/images/normal-scatter.png
    - classlib/classlib/quarto/slides/hickernell-slides.scss
    - classlib/classlib/quarto/website/hickernell-website.css
    - classlib/classlib/notebooks/**
    - classlib/classlib/quarto/js/stats-questions.js
    - classlib/classlib/quarto/css/stats-questions.css
    - classlib/classlib/notebooks/figures/**

metadata:
  instructor_photo: classlib/classlib/quarto/assets/images/fredplaidshirtcropped.jpg
    
# Navigation must live here (cannot be delegated via metadata-files).
# Styling/layout lives in HickernellClassLib (hickernell-website.yml).
website:
  title: "MATH 476 â€” Spring 2026"
  navbar:
    logo: /classlib/classlib/quarto/assets/images/normal-scatter.png
    left:
      - href: index.qmd
        text: Welcome
      - href: classlib/classlib/quarto/pages/stats-qs.qmd
        text: Stats Qs
      - href: pages/schedule.qmd
        text: Schedule
      - href: pages/notebooks.qmd
        text: Notebooks
      - href: pages/homework.qmd
        text: Assignments
      - href: pages/tests.qmd
        text: Tests
      - text: Resources
        menu:
          - href: classlib/classlib/quarto/pages/policies.qmd
            text: Policies
          - href: classlib/classlib/quarto/pages/git-clone-update-with-submodules.qmd
            text: Accessing repo
          - text: Interesting articles & links
            href: classlib/classlib/quarto/pages/interesting-articles-links.qmd
          - text: ðŸ†“ IMS Student Membershp
            href: https://imstat.org/free-student-membership/
          - text: ðŸ†“ SIAM Student Membership
            href: https://www.siam.org/membership/individual-membership/student-membership/
    right:
       - text: Related
         menu:
           - text: MATH 563 â€” Mathematical Statistics
             href: https://fjhickernell.github.io/MATH563Spring2026/
           - text: MATH 565 â€” Monte Carlo Methods
             href: https://QMCSoftware.github.io/MATH565Fall2025/
           - text: QMCPy
             href: https://qmcpy.github.io/
  page-footer:
    left: "Â© 2026 Fred J. Hickernell Â· Illinois Institute of Technology"

course:
  textbook:
      short: "Wackerly et al."
      full: "D. D. Wackerly, W. Mendenhall III, & R. L. Scheaffer, _Mathematical Statistics with Applications_, 7th Ed. (2008)"

execute:
  env:
    RETICULATE_PYTHON: ${HOME}/miniconda3/envs/qmcpy/bin/python
