project:
  type: website
  output-dir: docs

website:
  title: "MATH 476 — Spring 2026"
  navbar:
    left:
      - href: pages/index.qmd
        text: Home
      - href: pages/syllabus.qmd
        text: Syllabus
      - href: pages/schedule.qmd
        text: Schedule
      - href: pages/homework.qmd
        text: Homework
      - href: pages/resources.qmd
        text: Resources
      - href: slides/index.qmd
        text: Slides
  page-footer:
    left: "© 2026 Fred J. Hickernell"
    right: "Illinois Institute of Technology"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left