project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - pages/**/*.qmd
    - slides/**/*.qmd
  resources:
    - classlib/classlib/quarto/slides/hickernell-slides.css
    - classlib/classlib/quarto/slides/hickernell-latex-macros.js
    - classlib/classlib/quarto/assets/images/normal-scatter.png

metadata-files:
  - classlib/classlib/quarto/website/hickernell-website.yml

website:
  title: "MATH 476 â€” Spring 2026"